version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: devhub-postgres
    restart: always
    environment:
      POSTGRES_USER: devhub_user
      POSTGRES_PASSWORD: devhub_pass
      POSTGRES_DB: devhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
